name: CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Firebase Config Directory
        run: |
          mkdir -p src/main/resources/firebase
          echo "${{ secrets.FIREBASE_SERVICE_KEY }}" | base64 --decode > src/main/resources/firebase/firebaseServiceKey.json
        shell: bash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build -x test

      # Docker 관련 작업들은 push 시에만 실행되도록 설정
      - name: docker image build
        if: github.event_name == 'push'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/billilge:latest .

      # DockerHub 로그인
      - name: docker login
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Hub 이미지 푸시
      - name: docker Hub push
        if: github.event_name == 'push'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/billilge:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    #push 했을 때만 배포가 진행되도록
    if: github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/billilge:latest

      - name: docker stop container
        run: sudo docker stop springboot || true

      - name: docker run new container
        run: sudo docker run --env-file /home/ubuntu/billilge.env --name springboot --rm -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/billilge:latest

      - name: delete old docker image
        run: sudo docker image prune -f